name: stackfood_multivendor_driver
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.2
  connectivity_plus: ^6.0.5
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  firebase_auth: ^5.3.1
  path_provider: ^2.1.5
  url_strategy: ^0.3.0
  pin_code_fields: ^8.0.1
  http: ^1.3.0
  flutter_switch: ^0.3.2
  shimmer_animation: ^2.2.2
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  google_maps_flutter: ^2.11.0
  url_launcher: ^6.3.1
  vibration: ^3.1.3
  image_picker: ^1.1.2
#  disable_battery_optimization: ^1.1.1
  phone_numbers_parser: ^9.0.3
  country_code_picker: 3.0.0
  audioplayers: ^6.4.0
  flutter_widget_from_html_core: ^0.15.2
  intl: ^0.19.0
  path: ^1.9.0
  http_parser: ^4.1.2
  dotted_border: ^2.1.0
  photo_view: ^0.15.0
  flutter_inappwebview: ^6.1.5
  file_picker: ^9.2.1
  flutter_svg: ^2.0.17
  video_player: ^2.9.3
  chewie: ^1.11.0
  permission_handler: ^11.4.0
  url_launcher_ios: ^6.3.1
  flutter_foreground_task: ^8.17.0
  just_the_tooltip: ^0.0.12


dependency_overrides:
  collection: ^1.19.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3
    - assets/json/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900